# Generated by Django 5.2.4 on 2025-07-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Unique nickname of the player', max_length=100, unique=True, verbose_name='Nickname')),
                ('score', models.IntegerField(default=0, help_text='Accumulated score from assessments', verbose_name='Total score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['-score', 'nickname'],
            },
        ),
    ]
