# Generated by Django 5.2.4 on 2025-07-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_question_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='unique_id',
        ),
    ]
